### ISSUE TITLE
wrong number of saves in status bar

### ISSUE THREAD

**Issue by reyafyi** [coalaura/ctrl-s#1]
<img width="144" alt="image" src="https://github.com/coalaura/ctrl-s/assets/89781722/8156b88b-7e48-4d3e-a659-aafa939f1936"><br/>
<img width="405" alt="image" src="https://github.com/coalaura/ctrl-s/assets/89781722/7f285a38-e73b-4987-87f5-8a68f7dedaef">

looking at the code it seems that [here](https://github.com/coalaura/ctrl-s/blob/ee334cf27d8e1428882e3935f5bd01d009723245/src/format.js#L47-L58) you should use `1eX` instead of `10eX`. 

btw would be nice to have an option to always show the non-"short" number in the status bar, i really liked that

**Comment by coalaura** [comment]
should be all good now, also added this

![yes](https://i.shrt.day/L92D0MLQ39.webp)
